[package]
name = "prompt-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
parse-format = "0.1.0"
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = "2.0.60"
unindent = "0.2.3"
